Student answers screen
MicelloK/io pull request #38
Opened 2024-06-09 13:39 UTC by MicelloK

Jeszcze jest statyczne, bo nie ma endpointów. Na razie tylko anonimowa wersja

2024-06-09 15:45 UTC, MicelloK commented
Nie wiem, czy połączenie do api można zrobić w ten sposób, a nie mam jak przetestować. Najwyżej będzie do zmiany

2024-06-12 20:36 UTC, Kkaras1 approved these changes

2024-06-12 20:39 UTC, dominikpuz requested changes
troche juz dzisiaj siedzialem probując to poprawic bo nie dziala ale jeszcze mi sie nie udalo naprawic xD wiec niech nikt tego nie merguje czasem xD

2024-06-13 09:04 UTC, MicelloK commented
A siedzisz nad tym jeszcze, czy ja mam coś popatrzeć?

2024-06-13 09:05 UTC, dominikpuz commented
Możesz popatrzeć bo nwm czy będę mial czas

2024-06-13 11:01 UTC, closed without merging