Add remove student
MicelloK/io pull request #45
Opened 2024-06-12 16:36 UTC by Kkaras1

2024-06-12 20:55 UTC, maciek007 requested changes

2024-06-12 20:55 UTC, maciek007 commented on frontend/src/components/studentComponent.tsx
> +        removeStudent(name)
Tak jak Dominik Puz już wspominał, imię studenta powinno zawierać "%20" zmiast " ", bo ścieżka nie może zawierać spacji. Axios dodaje sam na miejsce spacji '+', nie jestem pewny czy java po przyjęciu takiej ścieżki z powrotem by zamienił '+' na ' ' (z tego co wstępnie patrzyłem to nie)

najprościej to naprawić poprzez
`name.replace(' ', "%20");`

2024-06-12 21:12 UTC, maciek007 approved these changes
Mimo spacji, przetestowane działa

2024-06-12 21:13 UTC, maciek007 approved these changes

2024-06-13 12:27 UTC, dominikpuz approved these changes

2024-06-13 12:28 UTC, merged